/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlideSlideIdRouteImport } from './routes/slide.$slideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideSlideIdRoute = SlideSlideIdRouteImport.update({
  id: '/slide/$slideId',
  path: '/slide/$slideId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slide/$slideId': typeof SlideSlideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slide/$slideId': typeof SlideSlideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slide/$slideId': typeof SlideSlideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slide/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slide/$slideId'
  id: '__root__' | '/' | '/slide/$slideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlideSlideIdRoute: typeof SlideSlideIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$slideId': {
      id: '/slide/$slideId'
      path: '/slide/$slideId'
      fullPath: '/slide/$slideId'
      preLoaderRoute: typeof SlideSlideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlideSlideIdRoute: SlideSlideIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
